# Generated by Django 3.0.3 on 2024-08-11 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20240811_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='daily_savings',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='loan_collected',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='remark',
        ),
    ]
